name: Docs
on: [push, pull_request, workflow_dispatch]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install Dependencies
        run: |
          pip install sphinx sphinx-book-theme
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Sphinx build
        run: |
          sphinx-apidoc -f -o docs . setup.py
          cd docs
          make html
          cd ..
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html/
          force_orphan: true
